### ISSUE TITLE
编译后运行不了

### ISSUE THREAD

**Issue by Lewiskong** [oceancx/SimpleEngine#1]
macos系统，编译成功，运行提示：
param: 1501.map
param: 49386FCE
param: 54F3FC94
param: DF749306
param: 1BEC0D8A
InitWDF:/Users/nirvana/Documents/C++Projects/github/SimpleEngine/Data/shape.wdf
number:2451 offset:255049336
WDF file load ok!
InitWDF:/Users/nirvana/Documents/C++Projects/github/SimpleEngine/Data/shape.wd3
number:912 offset:134629044
WDF file load ok!
 vPath:/Users/nirvana/Documents/C++Projects/github/SimpleEngine/Shader/sprite.vs
 fPath:/Users/nirvana/Documents/C++Projects/github/SimpleEngine/Shader/sprite.frag
 what 2
LoadShader
param: 1501.map
param: 49386FCE
param: 54F3FC94
param: DF749306
param: 1BEC0D8A
key: map 1501.map
key: shape.wd3 DF749306 1BEC0D8A
key: shape.wdf 49386FCE 54F3FC94
Width:5760	Height:2880
Row:12 Col:18
MAP文件初始化成功！
初始化GameMap 12 18 width: 512 height: 512
Sprite File Flag Error!

**Comment by oceancx** [comment]
Sprite File Flag Error! 是在WAS.cpp中的，感觉可能是shape资源文件上，这个文件是从百度云上下载的么？如果用官方客户端里的可能会有问题

**Comment by oceancx** [comment]
另外请检查一下Player.cpp里面写死的两个表，目前支持出Player的构造函数参数为（1，120）

**Comment by Lewiskong** [comment]
资源是从百度云上下载的，然后Player.cpp构造参数我没有改动呀。。还是不能运行

**Comment by oceancx** [comment]
我自己在mac上重新拉了一遍，是可以跑的，你有更新到最新代码么？不过鉴于目前版本不是很稳定，等我近期重新整理一下项目，再进行研究吧~

> param: 1501.map
> param: 49386FCE
> param: 54F3FC94
> param: DF749306
> param: 1BEC0D8A
> InitWDF:/Users/oceancx/SimpleEngine/Data/shape.wdf
> number:2451 offset:255049336
> WDF file load ok!
> InitWDF:/Users/oceancx/SimpleEngine/Data/shape.wd3
> number:912 offset:134629044
> WDF file load ok!
>  vPath:/Users/oceancx/SimpleEngine/Shader/sprite.vs
>  fPath:/Users/oceancx/SimpleEngine/Shader/sprite.frag
>  what 2
> LoadShader
> param: 1501.map
> param: 49386FCE
> param: 54F3FC94
> param: DF749306
> param: 1BEC0D8A
> key: map 1501.map
> key: shape.wd3 DF749306 1BEC0D8A
> key: shape.wdf 49386FCE 54F3FC94
> Width:5760	Height:2880
> Row:12 Col:18
> MAP文件初始化成功！
> 初始化GameMap 12 18 width: 512 height: 512
> HTTP/1.1 400 Bad Request
> Date: Mon, 16 Oct 2017 16:57:08 GMT
> Server: Apache/2.2.15 (CentOS)
> Content-Length: 306
> Connection: close
> Content-Type: text/html; charset=iso-8859-1
> <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
> <html><head>
> <title>400 Bad Request</title>
> </head><body>
> <h1>Bad Request</h1>
> <p>Your browser sent a request that this server could not understand.<br />
> </p>
> <hr>
> <address>Apache/2.2.15 (CentOS) Server at beta.boost.org Port 80</address>
> </body></html>
